"""
4_CONNECTIVITY/analyze.py
==========================
Computes transport and connectivity descriptors for 64x64x64 Ni-YSZ-Pore
voxel structures generated by the GAN-PH pipeline.

Metrics computed per structure:
  - Per-phase connectivity fraction  (scipy.ndimage.label, z-percolation)
  - Active TPB density               (µm⁻²)
  - Total TPB density                (µm⁻²) 
  - Per-phase tortuosity factor      (taufactor library)

Batch mode produces a CSV matching results.dat format, plus S-value
comparison between two datasets (e.g. real vs. GAN-generated).

Usage:
  # Single structure (for quick inspection)
  python analyze.py --input real_data/structure_0001

  # Full dataset
  python analyze.py --input real_data --output connectivity_results.csv

  # Compare two datasets (S-value analysis)
  python analyze.py --input real_data --compare generated_data
                    --output s_value_report.csv

Phase pixel values (must match preprocess_dream3d.py):
  Ni   = 255  (white)
  YSZ  = 127  (grey)
  Pore = 0    (black)
"""

import argparse
import csv
import sys
import warnings
from pathlib import Path

import cv2
import numpy as np
from scipy.ndimage import label
from scipy.stats import ks_2samp

# ── Config-driven constants ────────────────────────────────────────────────────
# Values are loaded from the anode_niysz config by default so that all scripts
# that import analyze.py (compute_tau_labels, validate_taufactor, ceiling_calibration,
# etc.) continue to work byte-identically with no --dataset-config flag.
# Pass --dataset-config <name> on any CLI entry point to switch datasets.

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from configs.dataset_config import get_config as _get_cfg, DatasetConfig

_ACTIVE_CFG: DatasetConfig = _get_cfg("anode_niysz")

_ch      = _ACTIVE_CFG.channel_names()       # ["Ni","YSZ","Pore"] for anode
NI_VAL   = _ACTIVE_CFG.phase_value(_ch[0])  # 255 — channel 0 (electron_conductor)
YSZ_VAL  = _ACTIVE_CFG.phase_value(_ch[1])  # 127 — channel 1 (ion_conductor)
PORE_VAL = _ACTIVE_CFG.phase_value(_ch[2])  # 0   — channel 2 (gas)
PHASES   = _ACTIVE_CFG.phases_dict()         # {"Ni": 255, "YSZ": 127, "Pore": 0}

VOXEL_SIZE_UM  = _ACTIVE_CFG.voxel_size_um  # 0.1 µm (100 nm, anode FIB-SEM)
VOXEL_VOL_UM3  = VOXEL_SIZE_UM ** 3
VOXEL_FACE_UM2 = VOXEL_SIZE_UM ** 2

# Threshold for S-value interpretation (Yu et al. 2025)
S_OK       = 0.85   # S ≥ 0.85 → highly similar, no feedback needed
S_MARGINAL = 0.70   # 0.70 ≤ S < 0.85 → moderate difference
                    # S < 0.70 → significant difference, feedback required

# Metrics reported as informational only — computed and shown but excluded from
# pass/fail scoring (Prof. Jin scope decision, 2026-07).
# tau_* were descoped because (a) tau_YSZ is intrinsically below MARGINAL even
# real-vs-real (ceiling=0.658), (b) tau_Ni/Pore are inversely coupled through
# softmax and cannot both reach MARGINAL simultaneously.
# YSZ quality is now scored via conn_YSZ (percolation fraction).
INFORMATIONAL_METRICS = {
    "tau_Ni", "tau_YSZ", "tau_Pore",
    # DPB metrics are informational for the anode (Prof. Jin: not a primary anode criterion).
    # For cathode config, dpb_informational=False removes them from this set.
    "dpb_Ni_YSZ", "dpb_Ni_Pore", "dpb_YSZ_Pore",
}

# Runs the DPB–SSA self-check exactly once (first structure analyzed per session).
_DPB_SSA_CHECKED: bool = False


def _apply_config(cfg: DatasetConfig) -> None:
    """Switch all module-level constants to a different dataset config.

    Called from main() when --dataset-config is passed. Updates NI_VAL,
    YSZ_VAL, PORE_VAL, PHASES, VOXEL_SIZE_UM and the derived area/volume
    constants so all downstream functions see the new values.
    """
    g = globals()
    _c = cfg.channel_names()
    g["_ACTIVE_CFG"]    = cfg
    g["NI_VAL"]         = cfg.phase_value(_c[0])
    g["YSZ_VAL"]        = cfg.phase_value(_c[1])
    g["PORE_VAL"]       = cfg.phase_value(_c[2])
    g["PHASES"]         = cfg.phases_dict()
    sz                  = cfg.voxel_size_um if cfg.voxel_size_um else 0.1
    g["VOXEL_SIZE_UM"]  = sz
    g["VOXEL_VOL_UM3"]  = sz ** 3
    g["VOXEL_FACE_UM2"] = sz ** 2
    # rebuild tau informational set with the new phase names
    info = {f"tau_{n}" for n in _c}
    # DPB metrics: informational for anode, scored for cathode
    if cfg.dpb_informational:
        for i in range(len(_c)):
            for j in range(i + 1, len(_c)):
                info.add(f"dpb_{_c[i]}_{_c[j]}")
                info.add(f"dpb_perc_{_c[i]}_{_c[j]}")
    g["INFORMATIONAL_METRICS"] = info


# ── 6-connectivity structure for scipy.ndimage.label ──────────────────────────

def _6conn():
    """Return a 3x3x3 boolean structuring element for 6-connectivity."""
    s = np.zeros((3, 3, 3), dtype=bool)
    s[1, 1, :] = True   # z-axis
    s[1, :, 1] = True   # y-axis
    s[:, 1, 1] = True   # x-axis
    return s


# ── I/O ───────────────────────────────────────────────────────────────────────

def load_structure(structure_dir: Path) -> np.ndarray:
    """
    Load a 64x64x64 structure from slice_XXXX.bmp files.

    Returns
    -------
    vol : np.ndarray, shape (64, 64, 64), dtype uint8
        Axis 0 = z (slice index), axes 1-2 = y, x.
    """
    bmp_files = sorted(structure_dir.glob("slice_*.bmp"))
    if not bmp_files:
        raise FileNotFoundError(
            f"No slice_*.bmp files found in {structure_dir}\n"
            f"Files present: {list(structure_dir.iterdir())[:8]}"
        )
    slices = []
    for f in bmp_files:
        img = cv2.imread(str(f), cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise IOError(f"Could not read {f}")
        slices.append(img)
    vol = np.stack(slices, axis=0).astype(np.uint8)
    if vol.shape[0] != 64 or vol.shape[1] != 64 or vol.shape[2] != 64:
        warnings.warn(
            f"Expected 64x64x64, got {vol.shape} in {structure_dir.name}"
        )
    return vol


def find_structure_dirs(data_dir: Path) -> list:
    """Return sorted list of structure_XXXX subdirectories."""
    dirs = sorted([
        p for p in data_dir.iterdir()
        if p.is_dir() and p.name.startswith("structure_")
    ])
    if not dirs:
        raise FileNotFoundError(
            f"No structure_XXXX directories found in {data_dir}"
        )
    return dirs


# ── Connectivity ──────────────────────────────────────────────────────────────

def compute_phase_connectivity(vol: np.ndarray, phase_val: int) -> float:
    """
    Percolation fraction: fraction of phase voxels that form a continuous
    path from z=0 face to z=63 face (electrode thickness direction).

    Parameters
    ----------
    vol       : 64x64x64 voxel array
    phase_val : pixel value identifying the phase (NI_VAL / YSZ_VAL / PORE_VAL)

    Returns
    -------
    float in [0.0, 1.0]
        0.0 = fully disconnected (or phase absent)
        1.0 = all phase voxels are in percolating components
    """
    binary = (vol == phase_val)
    total = int(binary.sum())
    if total == 0:
        return 0.0

    labeled, _ = label(binary, structure=_6conn())

    # Component labels on the z=0 and z=63 faces (only where phase is present)
    start_labels = set(labeled[0][binary[0]].tolist()) - {0}
    end_labels   = set(labeled[-1][binary[-1]].tolist()) - {0}

    percolating = start_labels & end_labels
    if not percolating:
        return 0.0

    percolating_voxels = int(np.isin(labeled, list(percolating)).sum())
    return percolating_voxels / total


def _get_percolating_mask(vol: np.ndarray, phase_val: int) -> np.ndarray:
    """
    Boolean mask: True where the phase voxel belongs to a z-percolating component.
    """
    binary = (vol == phase_val)
    if not binary.any():
        return np.zeros(vol.shape, dtype=bool)

    labeled, _ = label(binary, structure=_6conn())

    start_labels = set(labeled[0][binary[0]].tolist()) - {0}
    end_labels   = set(labeled[-1][binary[-1]].tolist()) - {0}
    percolating  = start_labels & end_labels

    if not percolating:
        return np.zeros(vol.shape, dtype=bool)

    return np.isin(labeled, list(percolating))


def _adjacent_to(mask: np.ndarray) -> np.ndarray:
    """
    Boolean array: True where a voxel has at least one 6-connected neighbor
    in `mask`. Uses np.roll (wraps at boundaries — negligible for 64^3).
    """
    return (
        np.roll(mask,  1, axis=0) | np.roll(mask, -1, axis=0) |
        np.roll(mask,  1, axis=1) | np.roll(mask, -1, axis=1) |
        np.roll(mask,  1, axis=2) | np.roll(mask, -1, axis=2)
    )


def compute_tpb_densities(vol: np.ndarray) -> tuple:
    """
    Compute total and active triple-phase boundary (TPB) densities.

    A voxel is a TPB site if it is adjacent (6-connectivity) to at least
    one voxel of each of the three phases simultaneously.

    A TPB site is ACTIVE if additionally all three adjacent phases are
    part of z-percolating components — meaning they can actually transport
    electrons, ions, and gas to/from the reaction site.

    Returns
    -------
    total_tpb_density  : float, µm⁻²
    active_tpb_density : float, µm⁻²
    active_fraction    : float in [0, 1]
        active_tpb / total_tpb (0 if total_tpb == 0)
    """
    ni_mask   = (vol == NI_VAL)
    ysz_mask  = (vol == YSZ_VAL)
    pore_mask = (vol == PORE_VAL)

    # Voxels adjacent to each phase
    adj_ni   = _adjacent_to(ni_mask)
    adj_ysz  = _adjacent_to(ysz_mask)
    adj_pore = _adjacent_to(pore_mask)

    # TPB site: adjacent to ALL three phases
    tpb_mask = adj_ni & adj_ysz & adj_pore

    # Percolating masks for each phase
    ni_perc   = _get_percolating_mask(vol, NI_VAL)
    ysz_perc  = _get_percolating_mask(vol, YSZ_VAL)
    pore_perc = _get_percolating_mask(vol, PORE_VAL)

    # Active TPB site: adjacent to PERCOLATING voxels of all three phases
    adj_ni_perc   = _adjacent_to(ni_perc)
    adj_ysz_perc  = _adjacent_to(ysz_perc)
    adj_pore_perc = _adjacent_to(pore_perc)

    active_tpb_mask = adj_ni_perc & adj_ysz_perc & adj_pore_perc

    total_vol_um3 = vol.size * VOXEL_VOL_UM3

    total_tpb  = float(tpb_mask.sum())  * VOXEL_FACE_UM2 / total_vol_um3
    active_tpb = float(active_tpb_mask.sum()) * VOXEL_FACE_UM2 / total_vol_um3

    active_frac = (active_tpb / total_tpb) if total_tpb > 0 else 0.0

    return total_tpb, active_tpb, active_frac


# ── Double-phase-boundary (DPB) interface densities ───────────────────────────

def _count_interface_faces(vol: np.ndarray, val_a: int, val_b: int) -> int:
    """
    Count 6-adjacent faces between phase A and phase B in vol.

    Convention: counts each face once, consistent with compute_surface_area in
    preprocess_dream3d.py (np.diff + np.abs on the phase mask along each axis).
    Identity that holds exactly (verified via _verify_dpb_ssa_consistency):
        sum_B( face_count(A, B) ) == surface_faces_A   [from compute_surface_area]
    """
    count = 0
    for ax in range(3):
        lo = np.take(vol, range(vol.shape[ax] - 1), axis=ax)
        hi = np.take(vol, range(1, vol.shape[ax]),  axis=ax)
        count += int(np.sum(((lo == val_a) & (hi == val_b)) |
                             ((lo == val_b) & (hi == val_a))))
    return count


def compute_dpb_densities(vol: np.ndarray) -> dict:
    """
    Double-phase-boundary (DPB) interface area densities (µm⁻¹, per total volume)
    for all phase pairs defined by the active config.

    Also computes percolation-weighted variants for pairs listed in
    _ACTIVE_CFG.reaction_pairs — the interface area where BOTH phases
    belong to z-percolating components (reusing _get_percolating_mask).

    Returns
    -------
    dict with keys:
        dpb_<A>_<B>        : float, µm⁻¹  (all interfaces between A and B)
        dpb_perc_<A>_<B>   : float, µm⁻¹  (percolating subset; only for reaction_pairs)
    """
    phase_items = list(PHASES.items())    # [(name, val), ...] in channel order
    total_vol_um3 = vol.size * VOXEL_VOL_UM3
    result = {}

    # Percolating masks — compute lazily only for phases that appear in reaction_pairs
    rp = _ACTIVE_CFG.reaction_pairs       # e.g. [["LSCF", "Pore"]]
    rp_names = {n for pair in rp for n in pair}
    perc_cache: dict[str, np.ndarray] = {}

    for i, (name_a, val_a) in enumerate(phase_items):
        for j, (name_b, val_b) in enumerate(phase_items):
            if j <= i:
                continue
            count = _count_interface_faces(vol, val_a, val_b)
            key = f"dpb_{name_a}_{name_b}"
            result[key] = float(count) * VOXEL_FACE_UM2 / total_vol_um3

            # Percolation-weighted variant for reaction pairs
            if name_a in rp_names and name_b in rp_names:
                # Check if this pair (in either order) is a requested reaction pair
                is_rp = any(
                    (set(p) == {name_a, name_b})
                    for p in rp
                )
                if is_rp:
                    if name_a not in perc_cache:
                        perc_cache[name_a] = _get_percolating_mask(vol, val_a)
                    if name_b not in perc_cache:
                        perc_cache[name_b] = _get_percolating_mask(vol, val_b)
                    pa = perc_cache[name_a]
                    pb = perc_cache[name_b]
                    count_perc = 0
                    for ax in range(3):
                        lo_vol = np.take(vol, range(vol.shape[ax] - 1), axis=ax)
                        hi_vol = np.take(vol, range(1, vol.shape[ax]),   axis=ax)
                        lo_pa  = np.take(pa,  range(pa.shape[ax]  - 1), axis=ax)
                        hi_pa  = np.take(pa,  range(1, pa.shape[ax]),   axis=ax)
                        lo_pb  = np.take(pb,  range(pb.shape[ax]  - 1), axis=ax)
                        hi_pb  = np.take(pb,  range(1, pb.shape[ax]),   axis=ax)
                        count_perc += int(np.sum(
                            ((lo_vol == val_a) & lo_pa & (hi_vol == val_b) & hi_pb) |
                            ((lo_vol == val_b) & lo_pb & (hi_vol == val_a) & hi_pa)
                        ))
                    perc_key = f"dpb_perc_{name_a}_{name_b}"
                    result[perc_key] = float(count_perc) * VOXEL_FACE_UM2 / total_vol_um3

    return result


def _verify_dpb_ssa_consistency(vol: np.ndarray, dpb: dict) -> None:
    """
    Self-check: verify sum_B( dpb_A_B ) == SSA_A × vf_A for each phase A.

    Both sides have units µm⁻¹ (area per TOTAL volume).
    Derivation:
        SSA_A  [µm⁻¹ per phase vol]  = surface_faces_A × face_area / vol_A
        dpb_A_B [µm⁻¹ per total vol] = face_AB × face_area / total_vol
        vf_A = vol_A / total_vol
        ∴  sum_B(dpb_A_B) = surface_faces_A × face_area / total_vol = SSA_A × vf_A

    Prints one line per phase confirming or flagging discrepancy.
    Uses the same face-counting approach as compute_surface_area (preprocess_dream3d).
    """
    phase_names = list(PHASES.keys())
    total_vox = vol.size
    for name_a, val_a in PHASES.items():
        mask_a = (vol == val_a).astype(np.int8)
        surface_faces_a = sum(int(np.sum(np.abs(np.diff(mask_a, axis=ax))))
                              for ax in range(3))
        # SSA_A × vf_A expressed per total volume — equals sum of DPB per total volume
        ssa_times_vf = surface_faces_a * VOXEL_FACE_UM2 / (total_vox * VOXEL_VOL_UM3)
        dpb_sum = sum(
            dpb.get(f"dpb_{name_a}_{nb}", 0) + dpb.get(f"dpb_{nb}_{name_a}", 0)
            for nb in phase_names if nb != name_a
        )
        delta = abs(dpb_sum - ssa_times_vf)
        ok = "OK" if delta < 1e-12 else f"MISMATCH delta={delta:.3e}"
        print(f"  DPB self-check {name_a}: sum(dpb)={dpb_sum:.6f}  "
              f"SSA×vf={ssa_times_vf:.6f}  [{ok}]")


# ── Tortuosity ────────────────────────────────────────────────────────────────

def compute_tortuosity(vol: np.ndarray, phase_val: int) -> float:
    """
    Tortuosity factor for a phase via the taufactor library.
    Solves steady-state diffusion (Laplace equation) on the phase's
    binary voxel grid using fixed Dirichlet BCs on z=0 and z=63 faces.

    Returns
    -------
    float
        Tortuosity factor τ. 1.0 = straight channel (ideal lower bound).
        Higher values = more tortuous transport path.
        Returns np.nan if the phase doesn't percolate or taufactor not installed.
    """
    try:
        import taufactor as tau
    except ImportError:
        warnings.warn(
            "taufactor not installed — tortuosity will be NaN.\n"
            "Install with: pip install taufactor"
        )
        return float("nan")

    binary = (vol == phase_val).astype(np.float32)

    # taufactor needs the phase to percolate; check first
    conn = compute_phase_connectivity(vol, phase_val)
    if conn == 0.0:
        return float("nan")   # no percolating path, tortuosity undefined

    try:
        solver = tau.Solver(binary)
        solver.solve()
        return float(np.asarray(solver.tau).flat[0])
    except Exception as e:
        warnings.warn(f"taufactor failed for phase {phase_val}: {e}")
        return float("nan")


# ── Full per-structure analysis ───────────────────────────────────────────────

def analyze_structure(vol: np.ndarray, compute_tau: bool = True) -> dict:
    """
    Run all connectivity metrics on a single 64x64x64 voxel array.

    Parameters
    ----------
    vol         : (64, 64, 64) uint8 numpy array
    compute_tau : bool, set False to skip tortuosity (slower computation)

    Returns
    -------
    dict with keys (names reflect active config's phase names):
        conn_<P0>, conn_<P1>, conn_<P2>        (float, z-percolation fractions)
        total_tpb, active_tpb, active_tpb_frac (float, µm⁻² / dimensionless)
        dpb_<Pa>_<Pb>                           (float, µm⁻¹, all phase pairs)
        dpb_perc_<Pa>_<Pb>                      (float, µm⁻¹, reaction_pairs only)
        tau_<P0>, tau_<P1>, tau_<P2>            (float, tortuosity factor)
    """
    global _DPB_SSA_CHECKED
    results = {}

    # Per-phase connectivity
    for name, val in PHASES.items():
        results[f"conn_{name}"] = compute_phase_connectivity(vol, val)

    # TPB densities
    total_tpb, active_tpb, active_frac = compute_tpb_densities(vol)
    results["total_tpb"]       = total_tpb
    results["active_tpb"]      = active_tpb
    results["active_tpb_frac"] = active_frac

    # DPB interface densities
    dpb = compute_dpb_densities(vol)
    results.update(dpb)

    # One-per-session self-check: verify sum(dpb_A_B) == SSA_A × vf_A
    if not _DPB_SSA_CHECKED:
        _DPB_SSA_CHECKED = True
        print("  [DPB self-check — runs once per session]")
        _verify_dpb_ssa_consistency(vol, dpb)

    # Tortuosity (informational; descoped 2026-07)
    if compute_tau:
        for name, val in PHASES.items():
            results[f"tau_{name}"] = compute_tortuosity(vol, val)
    else:
        for name in PHASES:
            results[f"tau_{name}"] = float("nan")

    return results


def analyze_dataset(data_dir: Path, compute_tau: bool = True,
                    verbose: bool = True) -> list:
    """
    Run analyze_structure on every structure_XXXX folder in data_dir.

    Returns
    -------
    list of dicts, one per structure, each with a 'name' key plus
    all keys from analyze_structure().
    """
    struct_dirs = find_structure_dirs(data_dir)
    all_results = []
    _names = list(PHASES.keys())   # phase names in channel order

    for sd in struct_dirs:
        if verbose:
            print(f"  Analyzing {sd.name} ...", end="", flush=True)
        vol = load_structure(sd)
        r = analyze_structure(vol, compute_tau=compute_tau)
        r["name"] = sd.name
        all_results.append(r)
        if verbose:
            conn_str = "  ".join(
                f"conn_{n}={r[f'conn_{n}']:.3f}" for n in _names
            )
            print(f" {conn_str}  active_tpb={r['active_tpb']:.3f} µm⁻²")

    return all_results


def save_results_csv(results: list, out_path: Path) -> None:
    """Write list-of-dicts results to a CSV file."""
    if not results:
        print("No results to write.")
        return

    fieldnames = ["name"] + [k for k in results[0] if k != "name"]
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)
    print(f"Saved {len(results)} rows → {out_path}")


# ── S-value (Yu et al. 2025) ──────────────────────────────────────────────────

def s_value(dist_a: np.ndarray, dist_b: np.ndarray,
            w_mu: float = 1.0,
            w_sigma: float = 1.0,
            w_ks: float = 1.0) -> float:
    """
    Weighted similarity index between two 1D distributions.

    From Yu et al. 2025 (Advanced Materials): compares mean, spread,
    and distributional shape. S=1.0 is identical, S=0.0 is maximally different.

    S ≥ 0.85  →  highly similar (OK)
    0.70 ≤ S < 0.85  →  moderate
    S < 0.70  →  significant difference (feedback required)

    Parameters
    ----------
    dist_a, dist_b : 1D arrays of measured values from two datasets
    w_mu, w_sigma, w_ks : weights (default 1.0 each, must sum to 3.0 total)
    """
    dist_a = np.asarray(dist_a, dtype=float)
    dist_b = np.asarray(dist_b, dtype=float)

    # Remove NaNs
    dist_a = dist_a[~np.isnan(dist_a)]
    dist_b = dist_b[~np.isnan(dist_b)]

    if len(dist_a) == 0 or len(dist_b) == 0:
        return float("nan")

    combined = np.concatenate([dist_a, dist_b])
    x_range = combined.max() - combined.min()

    # Mean discrepancy
    if x_range > 0:
        f_mu = abs(dist_a.mean() - dist_b.mean()) / x_range
    else:
        f_mu = 0.0

    # Spread (standard deviation) discrepancy
    diff_sigma = abs(dist_a.std() - dist_b.std())
    f_sigma = diff_sigma / (diff_sigma + 1.0)

    # Distributional shape (KS distance)
    ks_stat, _ = ks_2samp(dist_a, dist_b)
    f_ks = ks_stat / (ks_stat + 1.0)

    total_weight = w_mu + w_sigma + w_ks
    s = 1.0 - (1.0 / 3.0) * (
        w_mu * f_mu + w_sigma * f_sigma + w_ks * f_ks
    ) * (3.0 / total_weight)

    return float(np.clip(s, 0.0, 1.0))


def compare_datasets(results_real: list, results_gen: list) -> dict:
    """
    Compute S-values for every metric between two result sets.

    Returns a dict: {metric_name: {"s_value": float, "interpretation": str,
                                    "informational": bool}}

    The metrics list is derived dynamically from the result dicts so that
    dpb_* and conn_<phase> metrics work generically for any active config.
    Metrics in INFORMATIONAL_METRICS are flagged informational=True (not scored).
    """
    # Build metric list from result keys, preserving insertion order.
    # Exclude 'name'; skip any metric missing from either set (graceful degradation).
    all_keys = [k for k in results_real[0] if k != "name"]
    metrics = [m for m in all_keys
               if all(m in r for r in results_real)
               and all(m in r for r in results_gen)]

    def interp(s):
        if np.isnan(s):
            return "N/A (insufficient data)"
        elif s >= S_OK:
            return "OK — highly similar"
        elif s >= S_MARGINAL:
            return "MARGINAL — moderate difference"
        else:
            return "FAIL — significant difference"

    report = {}
    for m in metrics:
        real_vals = np.array([r[m] for r in results_real], dtype=float)
        gen_vals  = np.array([r[m] for r in results_gen],  dtype=float)
        s = s_value(real_vals, gen_vals)
        report[m] = {
            "s_value":       round(s, 4),
            "interpretation": interp(s),
            "informational":  m in INFORMATIONAL_METRICS,
        }

    return report


def print_comparison_report(report: dict, label_a: str = "Real",
                             label_b: str = "Generated") -> None:
    """Pretty-print the S-value comparison report.

    Scored metrics are shown first with pass/fail flags.
    Informational metrics (tau_*) are shown in a separate section — they are
    computed and reported but excluded from pass/fail scoring (2026-07 scope
    decision: tau descoped; YSZ scored via conn_YSZ percolation fraction).
    """
    scored = {m: v for m, v in report.items() if not v["informational"]}
    info   = {m: v for m, v in report.items() if v["informational"]}

    W = 66
    print(f"\n{'='*W}")
    print(f" S-value Comparison: {label_a}  vs  {label_b}")
    print(f" (Yu et al. 2025 framework)")
    print(f"{'='*W}")

    print(f" {'Metric':<22} {'S-value':>8}  {'Interpretation'}")
    print(f" {'-'*22} {'-'*8}  {'-'*34}")
    for metric, v in scored.items():
        s = v["s_value"]
        flag = "+" if s >= S_OK else ("~" if s >= S_MARGINAL else "!")
        print(f" [{flag}] {metric:<20} {s:>8.4f}  {v['interpretation']}")

    if info:
        print(f"\n --- Informational (not scored: tau descoped 2026-07; dpb informational for anode) ---")
        print(f" {'Metric':<22} {'S-value':>8}  {'Note'}")
        print(f" {'-'*22} {'-'*8}  {'-'*34}")
        for metric, v in info.items():
            s = v["s_value"]
            print(f" [i] {metric:<20} {s:>8.4f}  {v['interpretation']} (informational)")

    print(f"{'='*W}\n")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Connectivity and transport analysis for GAN-PH structures",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Inspect one structure quickly (no tortuosity, fast)
  python analyze.py --input real_data/structure_0001 --no-tau

  # Analyze whole dataset, save CSV
  python analyze.py --input real_data --output real_connectivity.csv

  # Compare real vs. GAN-generated (S-value report)
  python analyze.py --input real_data --compare generated_data
                    --output s_values.csv
"""
    )
    parser.add_argument("--input",   "-i", required=True,
                        help="Path to a single structure_XXXX dir OR a "
                             "parent folder containing multiple structure_XXXX dirs")
    parser.add_argument("--compare", "-c", default=None,
                        help="Second dataset to compare (for S-value report)")
    parser.add_argument("--output",  "-o", default=None,
                        help="CSV output path (optional)")
    parser.add_argument("--no-tau", action="store_true",
                        help="Skip tortuosity calculation (faster)")
    parser.add_argument("--dataset-config", default="anode_niysz",
                        metavar="NAME",
                        help="Dataset config name from configs/<NAME>.yaml "
                             "(default: anode_niysz — anode Ni-YSZ-Pore pipeline)")
    args = parser.parse_args()

    if args.dataset_config != "anode_niysz":
        _apply_config(_get_cfg(args.dataset_config))

    input_path = Path(args.input)
    compute_tau = not args.no_tau

    print("=" * 62)
    print(" GAN-PH Connectivity & Transport Analysis")
    print(f" Dataset config : {_ACTIVE_CFG.name}")
    print("=" * 62)

    # Single structure mode
    if input_path.name.startswith("structure_"):
        print(f"\nSingle structure: {input_path.name}")
        vol = load_structure(input_path)
        r = analyze_structure(vol, compute_tau=compute_tau)

        print(f"\n── Phase Connectivity (z-percolation fraction) ──")
        for name in PHASES:
            print(f"  {name:<6}: {r[f'conn_{name}']:.4f}")

        print(f"\n── Triple-Phase Boundary ──")
        print(f"  Total TPB density  : {r['total_tpb']:.4f} µm⁻²")
        print(f"  Active TPB density : {r['active_tpb']:.4f} µm⁻²")
        print(f"  Active fraction    : {r['active_tpb_frac']:.4f} "
              f"({r['active_tpb_frac']*100:.1f}%)")

        dpb_keys = [k for k in r if k.startswith("dpb_")]
        if dpb_keys:
            scored_flag = "" if _ACTIVE_CFG.dpb_informational else " [scored]"
            print(f"\n── Double-Phase Boundary (DPB){scored_flag} ──")
            for k in dpb_keys:
                info_tag = " [informational]" if _ACTIVE_CFG.dpb_informational else ""
                print(f"  {k:<28}: {r[k]:.4f} µm⁻¹{info_tag}")

        if compute_tau:
            print(f"\n── Tortuosity Factor (informational) ──")
            for name in PHASES:
                tau = r[f"tau_{name}"]
                s = f"{tau:.4f}" if not np.isnan(tau) else "N/A (non-percolating)"
                print(f"  {name:<6}: {s}")
        return

    # Dataset mode
    print(f"\nDataset: {input_path}")
    results_a = analyze_dataset(input_path, compute_tau=compute_tau)

    if args.output:
        save_results_csv(results_a, Path(args.output))

    # Comparison mode
    if args.compare:
        print(f"\nComparison dataset: {args.compare}")
        results_b = analyze_dataset(
            Path(args.compare), compute_tau=compute_tau
        )
        report = compare_datasets(results_a, results_b)
        print_comparison_report(
            report,
            label_a=input_path.name,
            label_b=Path(args.compare).name
        )
        if args.output:
            # Also save S-value report
            s_path = Path(args.output).with_stem(
                Path(args.output).stem + "_svalues"
            )
            rows = [
                {"metric": m, **v} for m, v in report.items()
            ]
            save_results_csv(rows, s_path)

    print("\nDone.")


if __name__ == "__main__":
    main()
