"""
4_CONNECTIVITY/analyze.py
==========================
Computes transport and connectivity descriptors for 64x64x64 Ni-YSZ-Pore
voxel structures generated by the GAN-PH pipeline.

Metrics computed per structure:
  - Per-phase connectivity fraction  (scipy.ndimage.label, z-percolation)
  - Active TPB density               (µm⁻²)
  - Total TPB density                (µm⁻²) 
  - Per-phase tortuosity factor      (taufactor library)

Batch mode produces a CSV matching results.dat format, plus S-value
comparison between two datasets (e.g. real vs. GAN-generated).

Usage:
  # Single structure (for quick inspection)
  python analyze.py --input real_data/structure_0001

  # Full dataset
  python analyze.py --input real_data --output connectivity_results.csv

  # Compare two datasets (S-value analysis)
  python analyze.py --input real_data --compare generated_data
                    --output s_value_report.csv

Phase pixel values (must match preprocess_dream3d.py):
  Ni   = 255  (white)
  YSZ  = 127  (grey)
  Pore = 0    (black)
"""

import argparse
import csv
import warnings
from pathlib import Path

import cv2
import numpy as np
from scipy.ndimage import label
from scipy.stats import ks_2samp

# ── Constants ──────────────────────────────────────────────────────────────────

NI_VAL   = 255
YSZ_VAL  = 127
PORE_VAL = 0
PHASES   = {"Ni": NI_VAL, "YSZ": YSZ_VAL, "Pore": PORE_VAL}

VOXEL_SIZE_UM = 0.1        # 100 nm per voxel (standard for FIB-SEM Ni-YSZ)
VOXEL_VOL_UM3 = VOXEL_SIZE_UM ** 3
VOXEL_FACE_UM2 = VOXEL_SIZE_UM ** 2

# Threshold for S-value interpretation (Yu et al. 2025)
S_OK       = 0.85   # S ≥ 0.85 → highly similar, no feedback needed
S_MARGINAL = 0.70   # 0.70 ≤ S < 0.85 → moderate difference
                    # S < 0.70 → significant difference, feedback required

# ── 6-connectivity structure for scipy.ndimage.label ──────────────────────────

def _6conn():
    """Return a 3x3x3 boolean structuring element for 6-connectivity."""
    s = np.zeros((3, 3, 3), dtype=bool)
    s[1, 1, :] = True   # z-axis
    s[1, :, 1] = True   # y-axis
    s[:, 1, 1] = True   # x-axis
    return s


# ── I/O ───────────────────────────────────────────────────────────────────────

def load_structure(structure_dir: Path) -> np.ndarray:
    """
    Load a 64x64x64 structure from slice_XXXX.bmp files.

    Returns
    -------
    vol : np.ndarray, shape (64, 64, 64), dtype uint8
        Axis 0 = z (slice index), axes 1-2 = y, x.
    """
    bmp_files = sorted(structure_dir.glob("slice_*.bmp"))
    if not bmp_files:
        raise FileNotFoundError(
            f"No slice_*.bmp files found in {structure_dir}\n"
            f"Files present: {list(structure_dir.iterdir())[:8]}"
        )
    slices = []
    for f in bmp_files:
        img = cv2.imread(str(f), cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise IOError(f"Could not read {f}")
        slices.append(img)
    vol = np.stack(slices, axis=0).astype(np.uint8)
    if vol.shape[0] != 64 or vol.shape[1] != 64 or vol.shape[2] != 64:
        warnings.warn(
            f"Expected 64x64x64, got {vol.shape} in {structure_dir.name}"
        )
    return vol


def find_structure_dirs(data_dir: Path) -> list:
    """Return sorted list of structure_XXXX subdirectories."""
    dirs = sorted([
        p for p in data_dir.iterdir()
        if p.is_dir() and p.name.startswith("structure_")
    ])
    if not dirs:
        raise FileNotFoundError(
            f"No structure_XXXX directories found in {data_dir}"
        )
    return dirs


# ── Connectivity ──────────────────────────────────────────────────────────────

def compute_phase_connectivity(vol: np.ndarray, phase_val: int) -> float:
    """
    Percolation fraction: fraction of phase voxels that form a continuous
    path from z=0 face to z=63 face (electrode thickness direction).

    Parameters
    ----------
    vol       : 64x64x64 voxel array
    phase_val : pixel value identifying the phase (NI_VAL / YSZ_VAL / PORE_VAL)

    Returns
    -------
    float in [0.0, 1.0]
        0.0 = fully disconnected (or phase absent)
        1.0 = all phase voxels are in percolating components
    """
    binary = (vol == phase_val)
    total = int(binary.sum())
    if total == 0:
        return 0.0

    labeled, _ = label(binary, structure=_6conn())

    # Component labels on the z=0 and z=63 faces (only where phase is present)
    start_labels = set(labeled[0][binary[0]].tolist()) - {0}
    end_labels   = set(labeled[-1][binary[-1]].tolist()) - {0}

    percolating = start_labels & end_labels
    if not percolating:
        return 0.0

    percolating_voxels = int(np.isin(labeled, list(percolating)).sum())
    return percolating_voxels / total


def _get_percolating_mask(vol: np.ndarray, phase_val: int) -> np.ndarray:
    """
    Boolean mask: True where the phase voxel belongs to a z-percolating component.
    """
    binary = (vol == phase_val)
    if not binary.any():
        return np.zeros(vol.shape, dtype=bool)

    labeled, _ = label(binary, structure=_6conn())

    start_labels = set(labeled[0][binary[0]].tolist()) - {0}
    end_labels   = set(labeled[-1][binary[-1]].tolist()) - {0}
    percolating  = start_labels & end_labels

    if not percolating:
        return np.zeros(vol.shape, dtype=bool)

    return np.isin(labeled, list(percolating))


def _adjacent_to(mask: np.ndarray) -> np.ndarray:
    """
    Boolean array: True where a voxel has at least one 6-connected neighbor
    in `mask`. Uses np.roll (wraps at boundaries — negligible for 64^3).
    """
    return (
        np.roll(mask,  1, axis=0) | np.roll(mask, -1, axis=0) |
        np.roll(mask,  1, axis=1) | np.roll(mask, -1, axis=1) |
        np.roll(mask,  1, axis=2) | np.roll(mask, -1, axis=2)
    )


def compute_tpb_densities(vol: np.ndarray) -> tuple:
    """
    Compute total and active triple-phase boundary (TPB) densities.

    A voxel is a TPB site if it is adjacent (6-connectivity) to at least
    one voxel of each of the three phases simultaneously.

    A TPB site is ACTIVE if additionally all three adjacent phases are
    part of z-percolating components — meaning they can actually transport
    electrons, ions, and gas to/from the reaction site.

    Returns
    -------
    total_tpb_density  : float, µm⁻²
    active_tpb_density : float, µm⁻²
    active_fraction    : float in [0, 1]
        active_tpb / total_tpb (0 if total_tpb == 0)
    """
    ni_mask   = (vol == NI_VAL)
    ysz_mask  = (vol == YSZ_VAL)
    pore_mask = (vol == PORE_VAL)

    # Voxels adjacent to each phase
    adj_ni   = _adjacent_to(ni_mask)
    adj_ysz  = _adjacent_to(ysz_mask)
    adj_pore = _adjacent_to(pore_mask)

    # TPB site: adjacent to ALL three phases
    tpb_mask = adj_ni & adj_ysz & adj_pore

    # Percolating masks for each phase
    ni_perc   = _get_percolating_mask(vol, NI_VAL)
    ysz_perc  = _get_percolating_mask(vol, YSZ_VAL)
    pore_perc = _get_percolating_mask(vol, PORE_VAL)

    # Active TPB site: adjacent to PERCOLATING voxels of all three phases
    adj_ni_perc   = _adjacent_to(ni_perc)
    adj_ysz_perc  = _adjacent_to(ysz_perc)
    adj_pore_perc = _adjacent_to(pore_perc)

    active_tpb_mask = adj_ni_perc & adj_ysz_perc & adj_pore_perc

    total_vol_um3 = vol.size * VOXEL_VOL_UM3

    total_tpb  = float(tpb_mask.sum())  * VOXEL_FACE_UM2 / total_vol_um3
    active_tpb = float(active_tpb_mask.sum()) * VOXEL_FACE_UM2 / total_vol_um3

    active_frac = (active_tpb / total_tpb) if total_tpb > 0 else 0.0

    return total_tpb, active_tpb, active_frac


# ── Tortuosity ────────────────────────────────────────────────────────────────

def compute_tortuosity(vol: np.ndarray, phase_val: int) -> float:
    """
    Tortuosity factor for a phase via the taufactor library.
    Solves steady-state diffusion (Laplace equation) on the phase's
    binary voxel grid using fixed Dirichlet BCs on z=0 and z=63 faces.

    Returns
    -------
    float
        Tortuosity factor τ. 1.0 = straight channel (ideal lower bound).
        Higher values = more tortuous transport path.
        Returns np.nan if the phase doesn't percolate or taufactor not installed.
    """
    try:
        import taufactor as tau
    except ImportError:
        warnings.warn(
            "taufactor not installed — tortuosity will be NaN.\n"
            "Install with: pip install taufactor"
        )
        return float("nan")

    binary = (vol == phase_val).astype(np.float32)

    # taufactor needs the phase to percolate; check first
    conn = compute_phase_connectivity(vol, phase_val)
    if conn == 0.0:
        return float("nan")   # no percolating path, tortuosity undefined

    try:
        solver = tau.Solver(binary)
        solver.solve()
        return float(solver.tau)
    except Exception as e:
        warnings.warn(f"taufactor failed for phase {phase_val}: {e}")
        return float("nan")


# ── Full per-structure analysis ───────────────────────────────────────────────

def analyze_structure(vol: np.ndarray, compute_tau: bool = True) -> dict:
    """
    Run all connectivity metrics on a single 64x64x64 voxel array.

    Parameters
    ----------
    vol         : (64, 64, 64) uint8 numpy array
    compute_tau : bool, set False to skip tortuosity (slower computation)

    Returns
    -------
    dict with keys:
        conn_Ni, conn_YSZ, conn_Pore          (float, connectivity fractions)
        total_tpb, active_tpb, active_tpb_frac (float, µm⁻²)
        tau_Ni, tau_YSZ, tau_Pore             (float, tortuosity factors)
    """
    results = {}

    # Per-phase connectivity
    for name, val in PHASES.items():
        results[f"conn_{name}"] = compute_phase_connectivity(vol, val)

    # TPB densities
    total_tpb, active_tpb, active_frac = compute_tpb_densities(vol)
    results["total_tpb"]       = total_tpb
    results["active_tpb"]      = active_tpb
    results["active_tpb_frac"] = active_frac

    # Tortuosity
    if compute_tau:
        for name, val in PHASES.items():
            results[f"tau_{name}"] = compute_tortuosity(vol, val)
    else:
        for name in PHASES:
            results[f"tau_{name}"] = float("nan")

    return results


def analyze_dataset(data_dir: Path, compute_tau: bool = True,
                    verbose: bool = True) -> list:
    """
    Run analyze_structure on every structure_XXXX folder in data_dir.

    Returns
    -------
    list of dicts, one per structure, each with a 'name' key plus
    all keys from analyze_structure().
    """
    struct_dirs = find_structure_dirs(data_dir)
    all_results = []

    for sd in struct_dirs:
        if verbose:
            print(f"  Analyzing {sd.name} ...", end="", flush=True)
        vol = load_structure(sd)
        r = analyze_structure(vol, compute_tau=compute_tau)
        r["name"] = sd.name
        all_results.append(r)
        if verbose:
            print(
                f" conn_Ni={r['conn_Ni']:.3f}  "
                f"conn_YSZ={r['conn_YSZ']:.3f}  "
                f"conn_Pore={r['conn_Pore']:.3f}  "
                f"active_tpb={r['active_tpb']:.3f} µm⁻²"
            )

    return all_results


def save_results_csv(results: list, out_path: Path) -> None:
    """Write list-of-dicts results to a CSV file."""
    if not results:
        print("No results to write.")
        return

    fieldnames = ["name"] + [k for k in results[0] if k != "name"]
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)
    print(f"Saved {len(results)} rows → {out_path}")


# ── S-value (Yu et al. 2025) ──────────────────────────────────────────────────

def s_value(dist_a: np.ndarray, dist_b: np.ndarray,
            w_mu: float = 1.0,
            w_sigma: float = 1.0,
            w_ks: float = 1.0) -> float:
    """
    Weighted similarity index between two 1D distributions.

    From Yu et al. 2025 (Advanced Materials): compares mean, spread,
    and distributional shape. S=1.0 is identical, S=0.0 is maximally different.

    S ≥ 0.85  →  highly similar (OK)
    0.70 ≤ S < 0.85  →  moderate
    S < 0.70  →  significant difference (feedback required)

    Parameters
    ----------
    dist_a, dist_b : 1D arrays of measured values from two datasets
    w_mu, w_sigma, w_ks : weights (default 1.0 each, must sum to 3.0 total)
    """
    dist_a = np.asarray(dist_a, dtype=float)
    dist_b = np.asarray(dist_b, dtype=float)

    # Remove NaNs
    dist_a = dist_a[~np.isnan(dist_a)]
    dist_b = dist_b[~np.isnan(dist_b)]

    if len(dist_a) == 0 or len(dist_b) == 0:
        return float("nan")

    combined = np.concatenate([dist_a, dist_b])
    x_range = combined.max() - combined.min()

    # Mean discrepancy
    if x_range > 0:
        f_mu = abs(dist_a.mean() - dist_b.mean()) / x_range
    else:
        f_mu = 0.0

    # Spread (standard deviation) discrepancy
    diff_sigma = abs(dist_a.std() - dist_b.std())
    f_sigma = diff_sigma / (diff_sigma + 1.0)

    # Distributional shape (KS distance)
    ks_stat, _ = ks_2samp(dist_a, dist_b)
    f_ks = ks_stat / (ks_stat + 1.0)

    total_weight = w_mu + w_sigma + w_ks
    s = 1.0 - (1.0 / 3.0) * (
        w_mu * f_mu + w_sigma * f_sigma + w_ks * f_ks
    ) * (3.0 / total_weight)

    return float(np.clip(s, 0.0, 1.0))


def compare_datasets(results_real: list, results_gen: list) -> dict:
    """
    Compute S-values for every metric between two result sets.

    Returns a dict: {metric_name: {"s_value": float, "interpretation": str}}
    """
    metrics = [
        "conn_Ni", "conn_YSZ", "conn_Pore",
        "total_tpb", "active_tpb", "active_tpb_frac",
        "tau_Ni", "tau_YSZ", "tau_Pore",
    ]

    def interp(s):
        if np.isnan(s):
            return "N/A (insufficient data)"
        elif s >= S_OK:
            return "OK — highly similar"
        elif s >= S_MARGINAL:
            return "MARGINAL — moderate difference"
        else:
            return "FAIL — significant difference (feedback required)"

    report = {}
    for m in metrics:
        real_vals = np.array([r[m] for r in results_real], dtype=float)
        gen_vals  = np.array([r[m] for r in results_gen],  dtype=float)
        s = s_value(real_vals, gen_vals)
        report[m] = {"s_value": round(s, 4), "interpretation": interp(s)}

    return report


def print_comparison_report(report: dict, label_a: str = "Real",
                             label_b: str = "Generated") -> None:
    """Pretty-print the S-value comparison report."""
    print(f"\n{'='*62}")
    print(f" S-value Comparison: {label_a}  vs  {label_b}")
    print(f" (Yu et al. 2025 framework)")
    print(f"{'='*62}")
    print(f" {'Metric':<22} {'S-value':>8}  {'Interpretation'}")
    print(f" {'-'*22} {'-'*8}  {'-'*34}")
    for metric, v in report.items():
        s = v["s_value"]
        flag = "✓" if s >= S_OK else ("~" if s >= S_MARGINAL else "✗")
        print(f" {flag} {metric:<20} {s:>8.4f}  {v['interpretation']}")
    print(f"{'='*62}\n")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Connectivity and transport analysis for GAN-PH structures",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Inspect one structure quickly (no tortuosity, fast)
  python analyze.py --input real_data/structure_0001 --no-tau

  # Analyze whole dataset, save CSV
  python analyze.py --input real_data --output real_connectivity.csv

  # Compare real vs. GAN-generated (S-value report)
  python analyze.py --input real_data --compare generated_data
                    --output s_values.csv
"""
    )
    parser.add_argument("--input",   "-i", required=True,
                        help="Path to a single structure_XXXX dir OR a "
                             "parent folder containing multiple structure_XXXX dirs")
    parser.add_argument("--compare", "-c", default=None,
                        help="Second dataset to compare (for S-value report)")
    parser.add_argument("--output",  "-o", default=None,
                        help="CSV output path (optional)")
    parser.add_argument("--no-tau", action="store_true",
                        help="Skip tortuosity calculation (faster)")
    args = parser.parse_args()

    input_path = Path(args.input)
    compute_tau = not args.no_tau

    print("=" * 62)
    print(" GAN-PH Connectivity & Transport Analysis")
    print("=" * 62)

    # Single structure mode
    if input_path.name.startswith("structure_"):
        print(f"\nSingle structure: {input_path.name}")
        vol = load_structure(input_path)
        r = analyze_structure(vol, compute_tau=compute_tau)

        print(f"\n── Phase Connectivity (z-percolation fraction) ──")
        for name in PHASES:
            print(f"  {name:<6}: {r[f'conn_{name}']:.4f}")

        print(f"\n── Triple-Phase Boundary ──")
        print(f"  Total TPB density  : {r['total_tpb']:.4f} µm⁻²")
        print(f"  Active TPB density : {r['active_tpb']:.4f} µm⁻²")
        print(f"  Active fraction    : {r['active_tpb_frac']:.4f} "
              f"({r['active_tpb_frac']*100:.1f}%)")

        if compute_tau:
            print(f"\n── Tortuosity Factor ──")
            for name in PHASES:
                tau = r[f"tau_{name}"]
                s = f"{tau:.4f}" if not np.isnan(tau) else "N/A (non-percolating)"
                print(f"  {name:<6}: {s}")
        return

    # Dataset mode
    print(f"\nDataset: {input_path}")
    results_a = analyze_dataset(input_path, compute_tau=compute_tau)

    if args.output:
        save_results_csv(results_a, Path(args.output))

    # Comparison mode
    if args.compare:
        print(f"\nComparison dataset: {args.compare}")
        results_b = analyze_dataset(
            Path(args.compare), compute_tau=compute_tau
        )
        report = compare_datasets(results_a, results_b)
        print_comparison_report(
            report,
            label_a=input_path.name,
            label_b=Path(args.compare).name
        )
        if args.output:
            # Also save S-value report
            s_path = Path(args.output).with_stem(
                Path(args.output).stem + "_svalues"
            )
            rows = [
                {"metric": m, **v} for m, v in report.items()
            ]
            save_results_csv(rows, s_path)

    print("\nDone.")


if __name__ == "__main__":
    main()
